Add wget2 patch

diff --git a/patch/wget2.patch b/patch/wget2.patch
--- a/patch/wget2.patch
+++ b/patch/wget2.patch
@@ -1,16 +1,29 @@
 --- bootstrap
 +++ bootstrap
-@@ -254,6 +254,13 @@
-       # presented with env variables to set to find the right version
-       ($2 --version </dev/null)
-     fi
-+  elif test "$1" = "-V"; then
-+    ($2 -V </dev/null) >/dev/null 2>&1
-+    if test $? -ge 126; then
-+      # If not found, run with diagnostics as one may be
-+      # presented with env variables to set to find the right version
-+      ($2 -V </dev/null)
-+    fi
-   else
-     ($1 --version </dev/null) >/dev/null 2>&1
-   fi
+@@ -469,6 +469,8 @@
+ 
+   $app --version >/dev/null 2>&1 || { $app --version; return 1; }
+ 
++  $app -V >/dev/null 2>&1 || { $app -V; return 1; }
++
+   $app --version 2>&1 | sed -n "$get_version_sed"
+ }
+ 
+@@ -523,12 +525,14 @@
+       # Merely require app to exist; not all prereq apps are well-behaved
+       # so we have to rely on $? rather than get_version.
+       if ! check_exists --verbose $app; then
+-        warn_ "Error: '$app' not found"
+-        ret=1
++        if ! check_exists -V $app; then
++          warn_ "Error: '$app' not found"
++          ret=1
++        fi
+       fi
+     else
+       # Require app to produce a new enough version string.
+-      inst_ver=$(get_version $app)
++      inst_ver=$(get_version $app 2>/dev/null)
+       if [ ! "$inst_ver" ]; then
+         warn_ "Error: '$app' not found"
+         ret=1
